server:
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/zxtest?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.zx.zxtest.*

logging:
  file: D:\\logs\zxtest.log
  level:
    com.zx.zxtest: debug
